### ISSUE TITLE
extension syntax alternatives

### ISSUE THREAD

**Issue by rtsao** [rtsao/csjs#1]
The optional extension syntactic sugar could trivially be switched to something like below (à la CSS Modules):

```javascript
csjs`
  .foo {
    color: green;
  }

  .bar {
    composes: foo, ${otherClass};
    padding: 4px;
  }
`
```

Current syntax:
```javascript
csjs`
  .foo {
    color: green;
  }

  .bar extends .foo, ${otherClass} {
      padding: 4px;
  }
`
```
Current syntax pros:
- Mimics "conventional" class inheritance syntax, including ES6 classes
- Clear separation from actual CSS properties and class composition

Current syntax cons:
- "Graceful degradation" as a plain CSS string fails badly (original selector fails)
  - *I don't think this is a big issue*

Overall, I think the choice is mostly arbitrary and there isn't much reason for one over the other beyond aesthetic preference.

**Comment by JaapRood** [comment]
Would be an option to support both? I'm looking into `csjs` basically because I want to prevent the build step CSS Modules requires, mainly to keep a simple project simple as it can be. Interoperability between the two, by supporting the same class composing syntax, would be great.

**Comment by rtsao** [comment]
For the sake of simplicity, I think I would prefer to stick to one syntax. The current syntax is simpler to handle in terms of parsing, which is nice. A CSS Modules composition syntax to CSJS extension syntax transform could probably be implemented with https://github.com/rtsao/babel-plugin-csjs-postcss and a PostCSS plugin without too much difficulty.
