### ISSUE TITLE
Support for more browsers

### ISSUE THREAD

**Issue by avesus** [rtsao/csjs#48]
`Object.assign()` is not supported even in IE11 and in iOS 7 and 8 (I know they are very buggy but they exist yet).
https://github.com/rtsao/csjs/blob/695d7820f61e7c6bae6b264f8bde3b8e444289dc/lib/csjs.js#L27

Please, rewrite that into something more supported.

**Comment by neurosnap** [comment]
Implementing a polyfill would be trivial without including external dependencies, but since it is only used once, there might be a more specific alternative to using `Object.assign`.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill

**Comment by scott113341** [comment]
Thanks for pointing that out, @avesus!  Here's a [compatibility table](http://kangax.github.io/compat-table/es6/#test-Object_static_methods_Object.assign) for `Object.assign`.

**Comment by rtsao** [comment]
Yeah, I meant to do this earlier but forgot. I'll fix this when I get a chance but a PR would also be happily accepted!

**Comment by rtsao** [comment]
Closed by #49
