### ISSUE TITLE
Is it possible to define #id style even if that's considered bad practice?

### ISSUE THREAD

**Issue by avesus** [rtsao/csjs#55]

**Comment by rtsao** [comment]
Yep, you can use IDs! However, they won't be scoped (they'll just get passed through to the CSS untouched) Hope that helps 😄

**Comment by avesus** [comment]
```
const style = csjs`

  # some_id {
    color: yellow;
  }
`;

style.some_id === undefined
```
And so it wasn't work for me... What I miss?

**Comment by rtsao** [comment]
Ah yes, the ID is never parsed (since it isn't a class), so it isn't scoped and is thus not provided in the returned object (that maps unscoped to scoped).

```js
const style = csjs`
  #some_id {
    color: yellow;
  }

  #another_id, .bar {
    color: green;
  }
`;
```

Then you can render something like:
```jsx
<div id="some_id">foo</div>
<div class={styles.bar}>bar</div>
```

**Comment by avesus** [comment]
Thank you very much fro the explanation! Great library, I use it in production and it's the only covers all composability patterns I was dreaming about. Very modular.
