### ISSUE TITLE
Dead code elimination

### ISSUE THREAD

**Issue by neurosnap** [rtsao/csjs#59]
If we don't use a class, can we eliminate it from the injectify/extractify output?

**Comment by rtsao** [comment]
Actually, I think this should be pretty easy to implement as a csjs loader for webpack 2.

**Comment by serapath** [comment]
I'm not sure if it makes sense, but after reading about `styletron`, maybe a minimal version can be used for `csjs`? It seems styletron does those kind of things already according to your blog post.

> An important part of CSS optimization is separating critical from non-critical CSS and eliminating unused CSS...
