### ISSUE TITLE
Release noScope?

### ISSUE THREAD

**Issue by bcomnes** [rtsao/csjs#66]
Do you have any ideas on when the noScope merge will make it into a release?  Thanks for a great module!

**Comment by drcmda** [comment]
Same question, npm says 1.0.6 just like on Github but the code is different.

**Comment by bcomnes** [comment]
On a sidenote, insert-css + vanilla class names seem to fill the gap till this lands.

**Comment by hareeqi** [comment]
@bcomnes  can you please clarify what you mean  by insert-css + vanilla class

thanks

**Comment by bcomnes** [comment]
E.G. loading unscoped css during the bundling process somehow (like https://github.com/substack/brfs) and using https://www.npmjs.com/package/insert-css directly.

**Comment by hareeqi** [comment]
thanks 👍

**Comment by neurosnap** [comment]
So even though the noScope has been merged in csjs, csjs-injectify and csjs-extractify probably still need to be modified to be accommodated for this release to happen.

**Comment by bcomnes** [comment]
> So even though the noScope has been merged in csjs, csjs-injectify and csjs-extractify probably still need to be modified to be accommodated for this release to happen.

I noticed this when trying to float a git dependency of HEAD.

**Comment by ungoldman** [comment]
:+1: would really like to use this feature without having to fork csjs 😓

**Comment by rtsao** [comment]
Gah, I got sidetracked on other things. I'll release this later today.

I was planning a bigger refactor and integrating this into those breaking changes, but that is going to be further down the line.

**Comment by rtsao** [comment]
Released as `v1.1.0`

**Comment by ungoldman** [comment]
Yay! Thanks @rtsao 🎈

**Comment by BenjaminVerble** [comment]
thanks @rtsao
